prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "career"
      - name: "publish"
        field:
          element: "text"
          label: "Published Date"
          value: "CURRENT_DATETIME"
      - name: "expire"
        field:
          element: "text"
          label: "Expiration Date"
          value: "CURRENT_DATETIME"